/** A Revive Adserver zone, as generated by Revive's own "Invocation code ->
 *  Asynchronous JS" tag (Publisher -> zone -> Generate invocation code). Each
 *  zone still needs `width`/`height` here — Revive's own tag carries neither,
 *  it just fills whatever box the `<ins>` sits in — so the slot can reserve
 *  space up front instead of shifting layout when the creative paints.
 *
 *  Rendered by `ReviveAdSlot`, which owns the shared `asyncjs.php` loader. */
export interface ReviveZone {
  zoneId: string;
  /** Revive's own `data-revive-id` for this zone's tag, as generated in
   *  Revive admin. All four zones below carry the SAME id — it is not a
   *  per-zone key, evidently a per-generation-session value from this
   *  install — so it is copied verbatim from each tag rather than assumed
   *  unique. Safe to hardcode either way: it is a fixed value from the
   *  generated snippet, not a per-request random one. */
  id: string;
  width: number;
  height: number;
  title: string;
}

// zoneId churned 1/2/3/4 -> 19/20/18/17 -> back to 1/2/3/4 on the ad server
// within 2026-08-12 alone — treat these ids as live config, not stable, and
// re-verify against `asyncspc.php?zones=<id>` (see ReviveAdSlot's doc
// comment) before trusting them if an ad stops appearing.

/** Portrait 390×660 — same slot shape as the self-hosted `kbPrasacPortrait`
 *  promo (see `@/lib/promos`), but served dynamically by Revive rather than a
 *  creative we host ourselves. */
export const revivePortrait: ReviveZone = {
  zoneId: "1",
  id: "55aa4b5dd75ab774bd198a60f6c237bc",
  width: 390,
  height: 660,
  title: "Revive ad — portrait",
};

/** Half landscape (short) 640×400 — same slot shape as
 *  `kbPrasacLandscapeShort` (see `@/lib/promos`). */
export const reviveLandscapeShort: ReviveZone = {
  zoneId: "2",
  id: "55aa4b5dd75ab774bd198a60f6c237bc",
  width: 640,
  height: 400,
  title: "Revive ad — half landscape (short)",
};

/** Half landscape 920×570 — same slot shape as `kbPrasacHalfLandscape` (see
 *  `@/lib/promos`). */
export const reviveHalfLandscape: ReviveZone = {
  zoneId: "3",
  id: "55aa4b5dd75ab774bd198a60f6c237bc",
  width: 920,
  height: 570,
  title: "Revive ad — half landscape",
};

/** Full landscape 1920×800 — same slot shape as `kbPrasacFullLandscape` (see
 *  `@/lib/promos`). */
export const reviveFullLandscape: ReviveZone = {
  zoneId: "4",
  id: "55aa4b5dd75ab774bd198a60f6c237bc",
  width: 1920,
  height: 800,
  title: "Revive ad — full landscape",
};
